import { Router, type IRouter } from "express";
import healthRouter from "./health";
import m365OverviewRouter from "./m365Overview";
import m365UsersRouter from "./m365Users";
import m365AdminExposureRouter from "./m365AdminExposure";
import m365LicensesRouter from "./m365Licenses";
import m365SecurityRouter from "./m365Security";
import m365ExchangeRouter from "./m365Exchange";
import m365TeamsRouter from "./m365Teams";
import m365SharePointRouter from "./m365SharePoint";
import m365SharePointPoliciesRouter from "./m365SharePointPolicies";
import m365ComplianceRouter from "./m365Compliance";
import m365ServiceHealthRouter from "./m365ServiceHealth";
import m365IntuneRouter from "./m365Intune";
import m365GroupsRouter from "./m365Groups";
import m365AppsRouter from "./m365Apps";
import m365ServicePrincipalsRouter from "./m365ServicePrincipals";
import m365PermissionsRouter from "./m365Permissions";
import m365DataSourcesRouter from "./m365DataSources";
import m365AdoptionRouter from "./m365Adoption";
import m365PowerBIRouter from "./m365PowerBI";
import onboardingRouter from "./onboarding";

const router: IRouter = Router();

router.use(healthRouter);
router.use(m365OverviewRouter);
router.use(m365UsersRouter);
router.use(m365AdminExposureRouter);
router.use(m365LicensesRouter);
router.use(m365SecurityRouter);
router.use(m365ExchangeRouter);
router.use(m365TeamsRouter);
router.use(m365SharePointRouter);
router.use(m365SharePointPoliciesRouter);
router.use(m365ComplianceRouter);
router.use(m365ServiceHealthRouter);
router.use(m365IntuneRouter);
router.use(m365GroupsRouter);
router.use(m365AppsRouter);
router.use(m365ServicePrincipalsRouter);
router.use(m365PermissionsRouter);
router.use(m365DataSourcesRouter);
router.use(m365AdoptionRouter);
router.use(m365PowerBIRouter);
router.use(onboardingRouter);

export default router;
